# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-07 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terraform', '0002_auto_20170627_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='deleted',
            field=models.DateTimeField(blank=True, default=None, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='historicalfile',
            name='deleted',
            field=models.DateTimeField(blank=True, default=None, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='historicalnamespace',
            name='deleted',
            field=models.DateTimeField(blank=True, default=None, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='historicaltemplate',
            name='deleted',
            field=models.DateTimeField(blank=True, default=None, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='historicaltemplateinstance',
            name='deleted',
            field=models.DateTimeField(blank=True, default=None, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='namespace',
            name='deleted',
            field=models.DateTimeField(blank=True, default=None, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='template',
            name='deleted',
            field=models.DateTimeField(blank=True, default=None, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='templateinstance',
            name='deleted',
            field=models.DateTimeField(blank=True, default=None, editable=False, null=True),
        ),
    ]
