# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-11 20:51
from __future__ import unicode_literals

from django.db import migrations, models
import estate.core.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('terraform', '0003_auto_20170707_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalnamespace',
            name='vault_backend',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='vault_backend'),
        ),
        migrations.AddField(
            model_name='namespace',
            name='vault_backend',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='vault_backend'),
        ),
        migrations.AlterField(
            model_name='file',
            name='slug',
            field=estate.core.models.fields.SoftDeleteAwareAutoSlugField(blank=True, editable=False, populate_from=b'title', verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='historicalfile',
            name='slug',
            field=estate.core.models.fields.SoftDeleteAwareAutoSlugField(blank=True, editable=False, populate_from=b'title', verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='historicalnamespace',
            name='slug',
            field=estate.core.models.fields.SoftDeleteAwareAutoSlugField(blank=True, editable=False, populate_from=b'title', verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='historicaltemplate',
            name='slug',
            field=estate.core.models.fields.SoftDeleteAwareAutoSlugField(blank=True, editable=False, populate_from=b'title', verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='historicaltemplateinstance',
            name='slug',
            field=estate.core.models.fields.SoftDeleteAwareAutoSlugField(blank=True, editable=False, populate_from=b'title', verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='namespace',
            name='slug',
            field=estate.core.models.fields.SoftDeleteAwareAutoSlugField(blank=True, editable=False, populate_from=b'title', verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='template',
            name='slug',
            field=estate.core.models.fields.SoftDeleteAwareAutoSlugField(blank=True, editable=False, populate_from=b'title', verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='templateinstance',
            name='slug',
            field=estate.core.models.fields.SoftDeleteAwareAutoSlugField(blank=True, editable=False, populate_from=b'title', verbose_name='slug'),
        ),
    ]
