# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-04 01:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terraform', '0004_auto_20170711_2051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalnamespace',
            name='vault_backend',
        ),
        migrations.RemoveField(
            model_name='namespace',
            name='vault_backend',
        ),
    ]
