# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-04 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terraform', '0005_auto_20170804_0146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalfile',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='historicalnamespace',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='historicaltemplate',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='historicaltemplateinstance',
            name='slug',
        ),
        migrations.AddField(
            model_name='historicalfile',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalnamespace',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicaltemplate',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicaltemplateinstance',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
